spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - AuthenticationFilter
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course-service/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
server:
  port: 9095
