spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: cms-users-service
          uri: lb://users-service
          predicates:
            - Path=/users-service/**
        - id: courses-service
          uri: lb://cms-courses-service
          predicates:
            - Path=/courses-service/**
server:
  port: 9095
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
