spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8082
  servlet:
    context-path: /user-service
  error:
    include-stacktrace: never