spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fvillanueva/atenea-properties
          default-label: main
          clone-on-start: true
server:
  port: 8888